// AUTO-GENERATED by scripts/gen-kind-registry.ts - do not edit by hand.
// Source: src/templates/codument/std/kinds/**/*.xnl

export const GENERATED_KIND_DEFINITIONS = {
  "AttractorProfiles": {
    "resourceId": "codument.resource_kind.AttractorProfiles",
    "resourceKind": "AttractorProfiles",
    "sourceShapes": [
      "single-file"
    ],
    "currentApiVersion": "codument.tech/v1alpha1",
    "supportedApiVersions": [
      "codument.tech/v1alpha1"
    ],
    "documentCardinality": "one"
  },
  "Behavior": {
    "resourceId": "codument.resource_kind.Behavior",
    "resourceKind": "Behavior",
    "sourceShapes": [
      "single-file"
    ],
    "currentApiVersion": "codument.tech/v1alpha1",
    "supportedApiVersions": [
      "codument.tech/v1alpha1"
    ],
    "documentCardinality": "one"
  },
  "BehaviorPatch": {
    "resourceId": "codument.resource_kind.BehaviorPatch",
    "resourceKind": "BehaviorPatch",
    "sourceShapes": [
      "single-file"
    ],
    "currentApiVersion": "codument.tech/v1alpha1",
    "supportedApiVersions": [
      "codument.tech/v1alpha1"
    ],
    "documentCardinality": "one"
  },
  "decision": {
    "resourceId": "codument.resource_kind.decision",
    "resourceKind": "decision",
    "sourceShapes": [
      "single-file"
    ],
    "currentApiVersion": "codument.tech/v1alpha1",
    "supportedApiVersions": [
      "codument.tech/v1alpha1"
    ],
    "documentCardinality": "many"
  },
  "EngineeringConfig": {
    "resourceId": "codument.resource_kind.EngineeringConfig",
    "resourceKind": "EngineeringConfig",
    "sourceShapes": [
      "single-file"
    ],
    "currentApiVersion": "codument.tech/v1alpha1",
    "supportedApiVersions": [
      "codument.tech/v1alpha1"
    ],
    "documentCardinality": "one"
  },
  "Mission": {
    "resourceId": "codument.resource_kind.Mission",
    "resourceKind": "Mission",
    "sourceShapes": [
      "directory"
    ],
    "currentApiVersion": "codument.tech/v1alpha1",
    "supportedApiVersions": [
      "codument.tech/v1alpha1"
    ],
    "documentCardinality": "one"
  },
  "ModelingConfig": {
    "resourceId": "codument.resource_kind.ModelingConfig",
    "resourceKind": "ModelingConfig",
    "sourceShapes": [
      "single-file"
    ],
    "currentApiVersion": "codument.tech/v1alpha1",
    "supportedApiVersions": [
      "codument.tech/v1alpha1"
    ],
    "documentCardinality": "one"
  },
  "OperationHooks": {
    "resourceId": "codument.resource_kind.OperationHooks",
    "resourceKind": "OperationHooks",
    "sourceShapes": [
      "single-file"
    ],
    "currentApiVersion": "codument.tech/v1alpha1",
    "supportedApiVersions": [
      "codument.tech/v1alpha1"
    ],
    "documentCardinality": "one"
  },
  "Track": {
    "resourceId": "codument.resource_kind.Track",
    "resourceKind": "Track",
    "sourceShapes": [
      "directory"
    ],
    "currentApiVersion": "codument.tech/v1alpha1",
    "supportedApiVersions": [
      "codument.tech/v1alpha1"
    ],
    "documentCardinality": "one"
  }
} as const;
