// AUTO-GENERATED by scripts/gen-template-manifest.ts — do not edit by hand.
// Regenerate after changing anything under src/templates/:
//   bun run scripts/gen-template-manifest.ts

import f0 from './codument/README.md' with { type: 'text' };
import f1 from './codument/attractors/product.md' with { type: 'text' };
import f2 from './codument/attractors/project.md' with { type: 'text' };
import f3 from './codument/backlog/README.md' with { type: 'text' };
import f4 from './codument/config/action-hooks.xml' with { type: 'text' };
import f5 from './codument/config/attractor-profiles.xml' with { type: 'text' };
import f6 from './codument/config/engineering.xml' with { type: 'text' };
import f7 from './codument/config/modeling.xml' with { type: 'text' };
import f8 from './codument/memory/README.md' with { type: 'text' };
import f9 from './codument/missions/README.md' with { type: 'text' };
import f10 from './codument/sop/README.md' with { type: 'text' };
import f11 from './codument/std/AGENTS.md' with { type: 'text' };
import f12 from './codument/std/actions/README.md' with { type: 'text' };
import f13 from './codument/std/actions/_action-spec.md' with { type: 'text' };
import f14 from './codument/std/actions/archive-mission.md' with { type: 'text' };
import f15 from './codument/std/actions/archive-track.md' with { type: 'text' };
import f16 from './codument/std/actions/artifact-sync.md' with { type: 'text' };
import f17 from './codument/std/actions/discuss.md' with { type: 'text' };
import f18 from './codument/std/actions/docs-bootstrap.md' with { type: 'text' };
import f19 from './codument/std/actions/gap-loop.md' with { type: 'text' };
import f20 from './codument/std/actions/impl-mission.md' with { type: 'text' };
import f21 from './codument/std/actions/impl-quick.md' with { type: 'text' };
import f22 from './codument/std/actions/impl-track.md' with { type: 'text' };
import f23 from './codument/std/actions/maintain-track.md' with { type: 'text' };
import f24 from './codument/std/actions/migrate.md' with { type: 'text' };
import f25 from './codument/std/actions/plan-mission.md' with { type: 'text' };
import f26 from './codument/std/actions/plan-track.md' with { type: 'text' };
import f27 from './codument/std/actions/validate.md' with { type: 'text' };
import f28 from './codument/std/actions/verify.md' with { type: 'text' };
import f29 from './codument/std/attractors/depa-attractor.md' with { type: 'text' };
import f30 from './codument/std/attractors/knowledge-tiers.md' with { type: 'text' };
import f31 from './codument/std/attractors/model-driven-docs.md' with { type: 'text' };
import f32 from './codument/std/attractors/project-memory.md' with { type: 'text' };
import f33 from './codument/std/commands/archive-track.md' with { type: 'text' };
import f34 from './codument/std/commands/modeling-engineering.md' with { type: 'text' };
import f35 from './codument/std/commands/upgrade-workspace.md' with { type: 'text' };
import f36 from './codument/std/compat/README.md' with { type: 'text' };
import f37 from './codument/std/kernel-pointer.md' with { type: 'text' };
import f38 from './codument/std/methods/dag-execution.md' with { type: 'text' };
import f39 from './codument/std/methods/tdd.md' with { type: 'text' };
import f40 from './codument/std/methods/workflow.md' with { type: 'text' };
import f41 from './codument/std/protocols/decision-tree.md' with { type: 'text' };
import f42 from './codument/std/protocols/questioning.md' with { type: 'text' };
import f43 from './codument/std/protocols/validation.md' with { type: 'text' };
import f44 from './codument/std/skill/docs-engineering-fractal/index.md' with { type: 'text' };
import f45 from './codument/std/skill/docs-modeling-fractal/index.md' with { type: 'text' };
import f46 from './codument/std/spec/behavior-delta.md' with { type: 'text' };
import f47 from './codument/std/spec/behavior-registry.md' with { type: 'text' };
import f48 from './codument/std/spec/decision-registry.md' with { type: 'text' };
import f49 from './codument/std/spec/engineering-delta.md' with { type: 'text' };
import f50 from './codument/std/spec/engineering-node-schema.md' with { type: 'text' };
import f51 from './codument/std/spec/engineering-registry.md' with { type: 'text' };
import f52 from './codument/std/spec/flow-notation.md' with { type: 'text' };
import f53 from './codument/std/spec/folder-manifest.md' with { type: 'text' };
import f54 from './codument/std/spec/mission-xml-spec.md' with { type: 'text' };
import f55 from './codument/std/spec/modeling-delta.md' with { type: 'text' };
import f56 from './codument/std/spec/modeling-node-schema.md' with { type: 'text' };
import f57 from './codument/std/spec/modeling-registry.md' with { type: 'text' };
import f58 from './codument/std/spec/track-xml-spec.md' with { type: 'text' };
import f59 from './codument/std/spec/xnl-format.md' with { type: 'text' };
import f60 from './codument/tracks/active/README.md' with { type: 'text' };
import f61 from './codument/tracks/archived/README.md' with { type: 'text' };
import f62 from './codument/tracks/pending/README.md' with { type: 'text' };
import f63 from './codument/workflows/README.md' with { type: 'text' };
import f64 from './skills/README.md' with { type: 'text' };
import f65 from './skills/codument-archive-mission/SKILL.md' with { type: 'text' };
import f66 from './skills/codument-archive-track/SKILL.md' with { type: 'text' };
import f67 from './skills/codument-artifact-sync/SKILL.md' with { type: 'text' };
import f68 from './skills/codument-discuss/SKILL.md' with { type: 'text' };
import f69 from './skills/codument-docs-bootstrap/SKILL.md' with { type: 'text' };
import f70 from './skills/codument-gap-loop/SKILL.md' with { type: 'text' };
import f71 from './skills/codument-impl-mission/SKILL.md' with { type: 'text' };
import f72 from './skills/codument-impl-quick/SKILL.md' with { type: 'text' };
import f73 from './skills/codument-impl-track/SKILL.md' with { type: 'text' };
import f74 from './skills/codument-maintain-track/SKILL.md' with { type: 'text' };
import f75 from './skills/codument-migrate/SKILL.md' with { type: 'text' };
import f76 from './skills/codument-migrate/references/decision-migration.md' with { type: 'text' };
import f77 from './skills/codument-plan-mission/SKILL.md' with { type: 'text' };
import f78 from './skills/codument-plan-track/SKILL.md' with { type: 'text' };
import f79 from './skills/codument-validate/SKILL.md' with { type: 'text' };
import f80 from './skills/codument-verify/SKILL.md' with { type: 'text' };

export interface TemplateFile {
  /** Path relative to src/templates/, e.g. "codument/std/AGENTS.md" or "skills/codument-track/SKILL.md". */
  path: string;
  content: string;
}

export const TEMPLATE_FILES: TemplateFile[] = [
  { path: "codument/README.md", content: f0 },
  { path: "codument/attractors/product.md", content: f1 },
  { path: "codument/attractors/project.md", content: f2 },
  { path: "codument/backlog/README.md", content: f3 },
  { path: "codument/config/action-hooks.xml", content: f4 },
  { path: "codument/config/attractor-profiles.xml", content: f5 },
  { path: "codument/config/engineering.xml", content: f6 },
  { path: "codument/config/modeling.xml", content: f7 },
  { path: "codument/memory/README.md", content: f8 },
  { path: "codument/missions/README.md", content: f9 },
  { path: "codument/sop/README.md", content: f10 },
  { path: "codument/std/AGENTS.md", content: f11 },
  { path: "codument/std/actions/README.md", content: f12 },
  { path: "codument/std/actions/_action-spec.md", content: f13 },
  { path: "codument/std/actions/archive-mission.md", content: f14 },
  { path: "codument/std/actions/archive-track.md", content: f15 },
  { path: "codument/std/actions/artifact-sync.md", content: f16 },
  { path: "codument/std/actions/discuss.md", content: f17 },
  { path: "codument/std/actions/docs-bootstrap.md", content: f18 },
  { path: "codument/std/actions/gap-loop.md", content: f19 },
  { path: "codument/std/actions/impl-mission.md", content: f20 },
  { path: "codument/std/actions/impl-quick.md", content: f21 },
  { path: "codument/std/actions/impl-track.md", content: f22 },
  { path: "codument/std/actions/maintain-track.md", content: f23 },
  { path: "codument/std/actions/migrate.md", content: f24 },
  { path: "codument/std/actions/plan-mission.md", content: f25 },
  { path: "codument/std/actions/plan-track.md", content: f26 },
  { path: "codument/std/actions/validate.md", content: f27 },
  { path: "codument/std/actions/verify.md", content: f28 },
  { path: "codument/std/attractors/depa-attractor.md", content: f29 },
  { path: "codument/std/attractors/knowledge-tiers.md", content: f30 },
  { path: "codument/std/attractors/model-driven-docs.md", content: f31 },
  { path: "codument/std/attractors/project-memory.md", content: f32 },
  { path: "codument/std/commands/archive-track.md", content: f33 },
  { path: "codument/std/commands/modeling-engineering.md", content: f34 },
  { path: "codument/std/commands/upgrade-workspace.md", content: f35 },
  { path: "codument/std/compat/README.md", content: f36 },
  { path: "codument/std/kernel-pointer.md", content: f37 },
  { path: "codument/std/methods/dag-execution.md", content: f38 },
  { path: "codument/std/methods/tdd.md", content: f39 },
  { path: "codument/std/methods/workflow.md", content: f40 },
  { path: "codument/std/protocols/decision-tree.md", content: f41 },
  { path: "codument/std/protocols/questioning.md", content: f42 },
  { path: "codument/std/protocols/validation.md", content: f43 },
  { path: "codument/std/skill/docs-engineering-fractal/index.md", content: f44 },
  { path: "codument/std/skill/docs-modeling-fractal/index.md", content: f45 },
  { path: "codument/std/spec/behavior-delta.md", content: f46 },
  { path: "codument/std/spec/behavior-registry.md", content: f47 },
  { path: "codument/std/spec/decision-registry.md", content: f48 },
  { path: "codument/std/spec/engineering-delta.md", content: f49 },
  { path: "codument/std/spec/engineering-node-schema.md", content: f50 },
  { path: "codument/std/spec/engineering-registry.md", content: f51 },
  { path: "codument/std/spec/flow-notation.md", content: f52 },
  { path: "codument/std/spec/folder-manifest.md", content: f53 },
  { path: "codument/std/spec/mission-xml-spec.md", content: f54 },
  { path: "codument/std/spec/modeling-delta.md", content: f55 },
  { path: "codument/std/spec/modeling-node-schema.md", content: f56 },
  { path: "codument/std/spec/modeling-registry.md", content: f57 },
  { path: "codument/std/spec/track-xml-spec.md", content: f58 },
  { path: "codument/std/spec/xnl-format.md", content: f59 },
  { path: "codument/tracks/active/README.md", content: f60 },
  { path: "codument/tracks/archived/README.md", content: f61 },
  { path: "codument/tracks/pending/README.md", content: f62 },
  { path: "codument/workflows/README.md", content: f63 },
  { path: "skills/README.md", content: f64 },
  { path: "skills/codument-archive-mission/SKILL.md", content: f65 },
  { path: "skills/codument-archive-track/SKILL.md", content: f66 },
  { path: "skills/codument-artifact-sync/SKILL.md", content: f67 },
  { path: "skills/codument-discuss/SKILL.md", content: f68 },
  { path: "skills/codument-docs-bootstrap/SKILL.md", content: f69 },
  { path: "skills/codument-gap-loop/SKILL.md", content: f70 },
  { path: "skills/codument-impl-mission/SKILL.md", content: f71 },
  { path: "skills/codument-impl-quick/SKILL.md", content: f72 },
  { path: "skills/codument-impl-track/SKILL.md", content: f73 },
  { path: "skills/codument-maintain-track/SKILL.md", content: f74 },
  { path: "skills/codument-migrate/SKILL.md", content: f75 },
  { path: "skills/codument-migrate/references/decision-migration.md", content: f76 },
  { path: "skills/codument-plan-mission/SKILL.md", content: f77 },
  { path: "skills/codument-plan-track/SKILL.md", content: f78 },
  { path: "skills/codument-validate/SKILL.md", content: f79 },
  { path: "skills/codument-verify/SKILL.md", content: f80 },
];
