#!/usr/bin/env bun
/**
 * Generates src/templates/manifest.ts: embeds every file under src/templates/
 * as a Bun text import so `codument init` / `upgrade-workspace` can write them
 * out from the compiled binary with no runtime filesystem dependency.
 *
 * Run: bun run scripts/gen-template-manifest.ts   (also wired into the build)
 */
import * as fs from 'fs';
import * as path from 'path';

const TEMPLATES_DIR = path.join(import.meta.dir, '..', 'src', 'templates');
const OUT = path.join(TEMPLATES_DIR, 'manifest.ts');
const SELF = 'manifest.ts';

function walk(dir: string, base: string): string[] {
  const out: string[] = [];
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      out.push(...walk(full, base));
    } else if (entry.isFile() && entry.name !== SELF) {
      out.push(path.relative(base, full).split(path.sep).join('/'));
    }
  }
  return out;
}

const files = walk(TEMPLATES_DIR, TEMPLATES_DIR).sort();

const header = [
  '// AUTO-GENERATED by scripts/gen-template-manifest.ts — do not edit by hand.',
  '// Regenerate after changing anything under src/templates/:',
  '//   bun run scripts/gen-template-manifest.ts',
  '',
];

const imports = files.map((rel, i) => `import f${i} from './${rel}' with { type: 'text' };`);

const entries = files.map((rel, i) => `  { path: ${JSON.stringify(rel)}, content: f${i} },`);

const body = [
  '',
  'export interface TemplateFile {',
  '  /** Path relative to src/templates/, e.g. "codument/std/AGENTS.md" or "skills/codument-track/SKILL.md". */',
  '  path: string;',
  '  content: string;',
  '}',
  '',
  'export const TEMPLATE_FILES: TemplateFile[] = [',
  ...entries,
  '];',
  '',
];

fs.writeFileSync(OUT, [...header, ...imports, ...body].join('\n'), 'utf-8');
console.log(`Generated ${path.relative(process.cwd(), OUT)} with ${files.length} embedded files.`);
