#!/usr/bin/env bun
import * as fs from 'fs';
import * as path from 'path';
import { loadResourceTree } from 'halfcode-compiler.xnl/resource-core';

const repoRoot = path.join(import.meta.dir, '..');
const authorityRoot = path.join(repoRoot, 'src', 'templates', 'codument', 'std', 'kinds');
const outputFile = path.join(repoRoot, 'src', 'cli', 'kinds', 'generated.ts');

const tree = await loadResourceTree({ rootDir: authorityRoot });
const definitions = [...tree.registry.kindDefinitions.values()]
  .sort((left, right) => left.resourceKind.localeCompare(right.resourceKind))
  .map((definition) => ({
    resourceId: definition.resourceId,
    resourceKind: definition.resourceKind,
    sourceShapes: definition.sourceShapes,
    currentApiVersion: definition.currentApiVersion,
    supportedApiVersions: definition.supportedApiVersions,
    documentCardinality: definition.documentCardinality,
  }));

const generated = `${[
  '// AUTO-GENERATED by scripts/gen-kind-registry.ts - do not edit by hand.',
  '// Source: src/templates/codument/std/kinds/**/*.xnl',
  '',
  `export const GENERATED_KIND_DEFINITIONS = ${JSON.stringify(Object.fromEntries(definitions.map((definition) => [definition.resourceKind, definition])), null, 2)} as const;`,
  '',
].join('\n')}`;

if (process.argv.includes('--check')) {
  const current = fs.existsSync(outputFile) ? fs.readFileSync(outputFile, 'utf8') : '';
  if (current !== generated) {
    console.error('Generated Codument Kind registry is stale. Run bun run gen:kinds.');
    process.exit(1);
  }
  console.log(`Checked ${definitions.length} Codument Kind definition(s).`);
} else {
  fs.mkdirSync(path.dirname(outputFile), { recursive: true });
  fs.writeFileSync(outputFile, generated, 'utf8');
  console.log(`Generated ${path.relative(repoRoot, outputFile)} from ${definitions.length} Kind definition(s).`);
}
